defaults:
  - _self_
  - preset: example
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

seed: 42
exp_name: "dbnet_training_train"
project_name: "dbnet_training"

wandb: True
exp_version: "dbnet_training_train"

resume: null

trainer:
  max_epochs: 10
  num_sanity_val_steps: 1
  log_every_n_steps: 50
  check_val_every_n_epoch: 1
  deterministic: True
