import os
from pathlib import Path

BASE_DIR = Path("my_photo_album")
folders = [
    "config", "data/raw_photos", "data/indexed_faces",
    "src", "templates", "static/results"
]

files = {
    "config/.my_config.yaml": """# 프로젝트 설정 파일
# 얼굴 인덱싱 및 검색 시스템용

data_path: data/raw_photos  # 원본 이미지 폴더 (label 없음)
cropped_faces_dir: data/indexed_faces  # 얼굴만 잘라 저장될 폴더
index_output: data/face_index.pkl  # 인덱싱 결과 저장 경로
face_model: cnn  # 'hog' 또는 'cnn' (정확도 우선이면 cnn 권장)
tolerance: 0.6  # 유사도 판단 기준 거리 임계값
top_k: null  # top_k 제한 없음 (전체 보여주기 위함)
use_copy: false  # 이미지 복사하지 않고 원본 사용
""",

    "templates/search.html": """<!DOCTYPE html>
<html>
<head><title>Face Search</title></head>
<body>
<h2>Upload a face to search</h2>
<form action=\"/search\" enctype=\"multipart/form-data\" method=\"post\">
  <input name=\"file\" type=\"file\" accept=\"image/*\">
  <input type=\"submit\">
</form>
<hr>
{% if results %}
<h3>Results:</h3>
<div style=\"display: flex; flex-wrap: wrap;\">
  {% for r in results %}
    <div style=\"margin: 5px; text-align: center;\">
      <img src=\"{{ r.path }}\" width=\"120\"><br>
      <small>{{ r.distance | round(3) }}</small>
    </div>
  {% endfor %}
</div>
{% endif %}
</body>
</html>
""",

    "src/config_loader.py": "import yaml\n\ndef load_config(path):\n    with open(path, 'r') as f:\n        return yaml.safe_load(f)\n",

    "README.md": """# 나의 사진첩
얼굴 인덱싱 + 검색 + 라벨링을 지원하는 Python 기반 시스템입니다.
- `data/raw_photos/`: 원본 사진
- `data/indexed_faces/`: 얼굴만 추출해 저장
- `face_index.pkl`: 인덱스 결과 파일
- 웹 기반 유사 얼굴 검색 (`face_search_web.py`)
"""
}


def create_structure():
    for folder in folders:
        (BASE_DIR / folder).mkdir(parents=True, exist_ok=True)
    for file_path, content in files.items():
        full_path = BASE_DIR / file_path
        with open(full_path, "w", encoding="utf-8") as f:
            f.write(content)
    print("✅ 'my_photo_album' 프로젝트 템플릿이 생성되었습니다!")


if __name__ == "__main__":
    create_structure()
