defaults:
  - _self_
  - preset: example
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

seed: 42
exp_name: "dbnet_training_test"
project_name: "dbnet_training"

wandb: true
exp_version: "_test"

checkpoint_path: null
